name: hostel_finder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core App Architecture
  get_it: ^8.0.3
  injectable: ^2.5.0
  build_runner: ^2.4.15
  provider: ^6.1.5

  # Data Storage & Networking
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  http: ^1.4.0
  connectivity_plus: ^6.1.4

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.6

  # Location & Maps
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.2
  image_picker: ^1.1.2

  # Image & Media
  camera: ^0.11.1
  flutter_image_compress: ^2.4.0

  # UI & UX
  auto_route: ^10.1.0
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1
  lottie: ^3.3.1
  flutter_screenutil: ^5.9.3
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - imgs/home_image.png
